repos:
-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    -   id: black
-   repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        args: ["--profile", "black"]

- repo: https://github.com/pre-commit/mirrors-clang-format.git
  rev: v14.0.6
  hooks:
  -   id: clang-format
      args: [--style=Google]
