name: cocotb-verification
run-name: Verification Workflow
on: [push]
jobs:
  cocotb-tests:
    env:
      SIM: icarus

    container: ghcr.io/ljhahne/cocotb:latest
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - run: python3 -m pytest -o log_cli=True --junitxml=test-results.xml --cocotbxml=test-cocotb.xml tests/
    - uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: test-results.xml

  report:
    needs: cocotb-tests
    container: bitnami/git:2.38.1-debian-11-r6
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Download Artifact
      uses: actions/download-artifact@v3
      with:
        name: test-results

    - run: git config --global --add safe.directory '*'
    - run: git init

    - name: Test Reporter
      uses: dorny/test-reporter@v1
      with:
        name: Test Results
        path: test-results.xml
        reporter: java-junit